In [1]:
import os
import sys
import warnings
warnings.filterwarnings('ignore')
# add the project root to the path so the src package can be imported
sys.path.append(os.path.abspath('..'))

import yaml
import numpy as np
from ultralytics import YOLO
from src.utils import apply_smart_aug
from src.model_utils import export_teeth_in_quad_using_enum_model,analyze_full_teeth_predictions,compare_best_vs_last,get_review_candidates,dedupe_gt_label_files

In [2]:
with open('../configs/stage2.yaml','r') as f:

    stage2_config = yaml.safe_load(f)


with open('../configs/stage2_continued.yaml','r') as f:

    stage2_cont_config = yaml.safe_load(f)


with open('../configs/stage3.yaml','r') as f:

    stage3_config = yaml.safe_load(f)


with open(stage2_config['model_args']['data'],'r') as f:

    enum_data_yaml = yaml.safe_load(f)


with open(stage2_cont_config['model_args']['data'],'r') as f:

    dis_data_yaml = yaml.safe_load(f)


with open('../configs/trained_models.yaml','r') as f:

    trained_models_config = yaml.safe_load(f)

In [3]:
dedupe_gt_label_files(dis_data_yaml['DISEASE_ONLY']['train'].replace('images','labels'),dry_run=False)

100%|██████████| 1439/1439 [00:00<00:00, 6509.20it/s]

Files with duplicates: 0 out of 1439

Empty DataFrame
Columns: []
Index: []

In [4]:
dedupe_gt_label_files(dis_data_yaml['DISEASE_ONLY']['val'].replace('images','labels'),dry_run=False)

100%|██████████| 181/181 [00:00<00:00, 7561.22it/s]

Files with duplicates: 0 out of 181

Empty DataFrame
Columns: []
Index: []

In [5]:
dedupe_gt_label_files(dis_data_yaml['DISEASE_ONLY']['test'].replace('images','labels'),dry_run=False)

100%|██████████| 175/175 [00:00<00:00, 7115.61it/s]

Files with duplicates: 0 out of 175

Empty DataFrame
Columns: []
Index: []

In [6]:
s2_test_results = compare_best_vs_last(enum_data_yaml,trained_models_config,
                                'enum',
                                'test',
                                main_result_path='../Runs/Stage 2/Enumeration Model Crop Analysis')

Running best and last weights on the test set (stage: enum)
enumeration_detection_model - best

100%|██████████| 248/248 [00:11<00:00, 22.41it/s]

Top 10 problematic images (most warnings):
  duplicates: 3, low_confidence: 1, missing: 132, leaks: 0, background: 0, successful: 8, avg_conf: 0.8237
enumeration_detection_model - last

100%|██████████| 248/248 [00:09<00:00, 26.33it/s]

Top 10 problematic images (most warnings):
  duplicates: 3, low_confidence: 0, missing: 132, leaks: 0, background: 0, successful: 6, avg_conf: 0.8833

Test set summary
enumeration_detection_model_best: total_errors=4, avg_confidence=0.8237
enumeration_detection_model_last: total_errors=3, avg_confidence=0.8833

Lowest total errors on test set: enumeration_detection_model_last with 3 errors

In [7]:
s3_train_results = compare_best_vs_last(dis_data_yaml['DISEASE_ONLY'],trained_models_config,
                                'enum',
                                'train',
                                main_result_path='../Runs/Stage 3/Enumeration Model Crop Analysis')

Running best and last weights on the test set (stage: enum)
enumeration_detection_model - best

100%|██████████| 1439/1439 [00:54<00:00, 26.19it/s]

Top 10 problematic images (most warnings):
  duplicates: 240, low_confidence: 126, missing: 834, leaks: 166, background: 1, successful: 7613, avg_conf: 0.9205
enumeration_detection_model - last

100%|██████████| 1439/1439 [00:54<00:00, 26.45it/s]

Top 10 problematic images (most warnings):
  duplicates: 176, low_confidence: 103, missing: 831, leaks: 161, background: 1, successful: 7617, avg_conf: 0.9372

Test set summary
enumeration_detection_model_best: total_errors=533, avg_confidence=0.9205
enumeration_detection_model_last: total_errors=441, avg_confidence=0.9372

Lowest total errors on test set: enumeration_detection_model_last with 441 errors

In [8]:
s3_valid_results = compare_best_vs_last(dis_data_yaml['DISEASE_ONLY'],trained_models_config,
                                'enum',
                                'valid',
                                main_result_path='../Runs/Stage 3/Enumeration Model Crop Analysis')

Running best and last weights on the test set (stage: enum)
enumeration_detection_model - best

100%|██████████| 181/181 [00:07<00:00, 25.44it/s]

Top 10 problematic images (most warnings):
  duplicates: 23, low_confidence: 16, missing: 104, leaks: 17, background: 0, successful: 963, avg_conf: 0.9171
enumeration_detection_model - last

100%|██████████| 181/181 [00:06<00:00, 25.89it/s]

Top 10 problematic images (most warnings):
  duplicates: 27, low_confidence: 16, missing: 103, leaks: 15, background: 0, successful: 965, avg_conf: 0.9309

Test set summary
enumeration_detection_model_best: total_errors=56, avg_confidence=0.9171
enumeration_detection_model_last: total_errors=58, avg_confidence=0.9309

Lowest total errors on test set: enumeration_detection_model_best with 56 errors

In [9]:
s3_test_results = compare_best_vs_last(dis_data_yaml['DISEASE_ONLY'],trained_models_config,
                                'enum',
                                'test',
                                main_result_path='../Runs/Stage 3/Enumeration Model Crop Analysis')

Running best and last weights on the test set (stage: enum)
enumeration_detection_model - best

100%|██████████| 175/175 [00:07<00:00, 24.46it/s]

Top 10 problematic images (most warnings):
  duplicates: 23, low_confidence: 12, missing: 93, leaks: 25, background: 0, successful: 953, avg_conf: 0.9252
enumeration_detection_model - last

100%|██████████| 175/175 [00:07<00:00, 24.71it/s]

Top 10 problematic images (most warnings):
  duplicates: 18, low_confidence: 11, missing: 87, leaks: 22, background: 0, successful: 960, avg_conf: 0.9410

Test set summary
enumeration_detection_model_best: total_errors=60, avg_confidence=0.9252
enumeration_detection_model_last: total_errors=51, avg_confidence=0.9410

Lowest total errors on test set: enumeration_detection_model_last with 51 errors