In [1]:
import os
import sys
import warnings
warnings.filterwarnings('ignore')
# add the project root to the path so the src package can be imported
sys.path.append(os.path.abspath('..'))

import yaml
import numpy as np
from ultralytics import YOLO
from src.utils import apply_smart_aug
from src.model_utils import export_teeth_in_quad_using_enum_model,analyze_full_teeth_predictions,compare_best_vs_last,get_review_candidates,dedupe_gt_label_files

In [2]:
with open('../configs/stage2.yaml','r') as f:

    stage2_config = yaml.safe_load(f)


with open('../configs/stage2_continued.yaml','r') as f:

    stage2_cont_config = yaml.safe_load(f)


with open('../configs/stage3.yaml','r') as f:

    stage3_config = yaml.safe_load(f)


with open(stage2_config['model_args']['data'],'r') as f:

    enum_data_yaml = yaml.safe_load(f)


with open(stage2_cont_config['model_args']['data'],'r') as f:

    dis_data_yaml = yaml.safe_load(f)


with open('../configs/trained_models.yaml','r') as f:

    trained_models_config = yaml.safe_load(f)

In [3]:
dedupe_gt_label_files(dis_data_yaml['DISEASE_ONLY']['train'].replace('images','labels'),dry_run=False)

100%|██████████| 1439/1439 [00:00<00:00, 6509.20it/s]

Files with duplicates: 0 out of 1439

Empty DataFrame
Columns: []
Index: []

In [4]:
dedupe_gt_label_files(dis_data_yaml['DISEASE_ONLY']['val'].replace('images','labels'),dry_run=False)

100%|██████████| 181/181 [00:00<00:00, 7561.22it/s]

Files with duplicates: 0 out of 181

Empty DataFrame
Columns: []
Index: []

In [5]:
dedupe_gt_label_files(dis_data_yaml['DISEASE_ONLY']['test'].replace('images','labels'),dry_run=False)

100%|██████████| 175/175 [00:00<00:00, 7115.61it/s]

Files with duplicates: 0 out of 175

Empty DataFrame
Columns: []
Index: []